const data = [
  { name: "百度", link: "https://www.baidu.com", image:"baidu.png" },
  { name: "Google", link: "https://www.google.com/", image:"google.png" },
  { name: "搜狗", link: "https://www.sogou.com/", image:"sogou.png" },
  { name: "Pinterest", link: "https://www.pinterest.com/", image:"pinterest.png" },
  { name: "dribbble", link: "https://dribbble.com/", image:"dribbble.png" },
  { name: "花瓣", link: "https://huaban.com/", image:"huaban.png" },
  { name: "Behance", link: "https://www.behance.net/", image:"behance.png" },
  { name: "Uisdc", link: "https://www.uisdc.com/", image:"uisdc.png" },
  { name: "站酷", link: "https://www.zcool.com.cn/", image:"zcool.png" },
  { name: "千图", link: "https://www.58pic.com/", image:"qiantu.png" },
  { name: "字由", link: "http://www.hellofont.cn/", image:"ziyou.png" },
  { name: "美叶", link: "https://www.meiye.art/inspiration", image:"meiye.png" },

  { name: "摄影资源馆", link: "http://sheyingzyg.com/", image:"syzyg.png" },


  { name: "thosefree", link: "https://www.thosefree.com/", image:"thosefree.png" },

  { name: "海螺创意", link: "https://www.hellorf.com/", image:"hailuo.jpg" },
  { name: "BiliBili", link: "https://www.bilibili.com/", image:"bilibili.png" },
  { name: "百度翻译", link: "https://fanyi.baidu.com/", image:"baiduyi.png" },
  { name: "百度云盘", link: "https://pan.baidu.com", image:"baidupan.png" },
  { name: "twitter", link: "http://www.twitter.com/", image:"twitter.png" },
  { name: "ins", link: "https://www.instagram.com/", image:"ins.png" },
  { name: "Youtube", link: "https://www.youtube.com", image:"YouTube.png" },
  { name: "Vimeo", link: "https://vimeo.com/", image:"vimeo.png" },
  { name: "linestore", link: "https://store.line.me/home/zh-Hans", image:"linestore.png" },
  { name: "淘宝", link: "https://www.taobao.com/", image:"taobao.png" },
  { name: "微博", link: "https://weibo.com/", image:"weibo.png" },
  { name: "QQ邮箱", link: "https://mail.qq.com/", image:"qqmail.png" },
  { name: "微信公众号", link: "https://mp.weixin.qq.com/", image:"wx01.png" },
  { name: "微信表情", link: "https://sticker.weixin.qq.com", image:"wx02.png" },
  { name: "Apple", link: "https://www.apple.com.cn/", image:"apple.png" },
  { name: "豆瓣", link: "https://www.douban.com/", image:"douban.png" },
  { name: "语雀", link: "https://www.yuque.com/dashboard", image:"yuque.jpg" },
  { name: "outlook", link: "https://outlook.live.com/", image:"outlook.jpg" },
]